[versions]
android-plugin = "8.1.0"
androidx-compose = "1.6.0-alpha02"
kotlin = "1.8.22"
material3 = "1.2.0-alpha04"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.7.2" }
androidx-core = { module = "androidx.core:core-ktx", version = "1.10.1" }
androidx-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androidx-compose" }
androidx-ui-graphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "androidx-compose" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }